# Generated by Django 4.1.7 on 2023-04-08 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App1', '0002_upload_book'),
    ]

    operations = [
        migrations.AddField(
            model_name='upload_book',
            name='cover',
            field=models.ImageField(blank=True, null=True, upload_to='uploadedBooks/covers/'),
        ),
    ]
